config/routes.rb
Rhinogallery::Engine.routes.draw do

  scope "(:locale)", locale: /ru|en/ do

    resources :galleries do
      get 'load_images' => 'galleries#load_images', :on => :member
      get 'move_up' => 'galleries#move_up', :on => :member
      get 'move_down' => 'galleries#move_down', :on => :member
      resources :images
    end

    resources :images, :only => [:destroy]

  end

end

app/models/rhinogallery/common.rb
module Rhinogallery
	class Common < ActiveRecord::Base
		self.abstract_class = true

		def last_version_change_user
			if defined?(translation) && translation.versions.last.present?
				begin
					Rhinoart::User.find translation.versions.last.whodunnit.to_i	
				rescue
				end			
			else
				begin
					Rhinoart::User.find versions.last.whodunnit.to_i	
				rescue
				end			
			end
		end

		def last_version_change_date
			if defined?(translation) && translation.versions.last.present?
				begin
					translation.versions.last.created_at
				rescue				
				end			
			else
				begin
					versions.last.created_at	
				rescue				
				end			
			end
		end
	end
end

app/models/rhinogallery/gallery.rb
# == Schema Information
#
# Table name: rhinogallery_galleries
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  slug        :string(255)      not null
#  description :text(65535)
#  image       :string(255)
#  position    :integer
#  active      :boolean          default(TRUE)
#  created_at  :datetime
#  updated_at  :datetime
#

module Rhinogallery
  class Gallery < Rhinogallery::Common
    mount_uploader :image, Rhinogallery::ImageUploader

    before_validation :build_slug

    extend FriendlyId
    friendly_id :slug, use: [:slugged, :finders]

    acts_as_list
    has_paper_trail

    default_scope { order('position') }
    scope :active, ->{ where(active: true ) }

    has_many :images, class_name: 'Rhinogallery::Image', dependent: :destroy

    validates :name, :length => { :in => 2..150 }
    validates :slug, :length => { :in => 2..150 }, :uniqueness => true
    # validates :image, :presence => true

    protected
        def build_slug
            if !self.slug.present?
                self.slug = Rhinoart::Utils.to_slug(self.name)
            else
                self.slug = Rhinoart::Utils.to_slug(self.slug)
            end
        end 
  end
end

app/models/rhinogallery/image.rb
# == Schema Information
#
# Table name: rhinogallery_images
#
#  id          :integer          not null, primary key
#  name        :string(255)      not null
#  description :text(65535)
#  image       :string(255)      not null
#  alt         :string(255)
#  position    :integer
#  active      :boolean
#  gallery_id  :integer
#  created_at  :datetime         not null
#  tags        :string(255)
#  rightholder :string(255)
#  selfright   :integer
#  info        :text(65535)
#

module Rhinogallery
  class Image < Rhinogallery::Common
    before_validation :set_rights
    mount_uploader :image, Rhinogallery::ImageUploader

    UPDATE_AVAILABLE_ATTRIBUTES = [:name, :alt, :description, :active, :image, :tags, :selfright, :rightholder, :position]
    RIGHTHOLDER_TYPES = {
        I18n.t(:empty) => :empty, 
        I18n.t(:self_right) => :self_right, 
        I18n.t(:stock) => :stock, 
        I18n.t(:public_domain) => :public_domain, 
    }
    acts_as_list scope: :gallery_id
    has_paper_trail

    # default_scope { order 'position' }
    scope :active, ->{ where(active: true ) }

    belongs_to :gallery, class_name: 'Rhinogallery::Gallery'
    validates :name, :length => { :in => 2..150 }
    validates :image, :gallery_id, presence: true

    def self.add_edited_fields(*fields)
      UPDATE_AVAILABLE_ATTRIBUTES.push(*fields)
    end

    private

        def set_rights
            self.rightholder = nil if self.selfright.to_i == 1
            self.selfright = nil if self.rightholder.present?
        end
  end
end

app/controllers/rhinogallery/application_controller.rb
require_dependency "rhinoart/base_controller"
module Rhinogallery
  class ApplicationController < Rhinoart::BaseController

    layout 'rhinoart/application'

  end
end

app/controllers/rhinogallery/galleries_controller.rb
require_dependency "rhinogallery/application_controller"
module Rhinogallery
	class GalleriesController < ApplicationController
		before_action { authorize!(:manage, Rhinogallery::Gallery) }
		before_action :set_gallery, only: [:show, :edit, :update, :destroy, :load_images, :move_up, :move_down]

		# GET /galleries
		def index
			@galleries = Rhinogallery::Gallery.includes(:images).all
		end

		# GET /galleries/1
		def show
			if params[:search].present? && (params[:q].present? || params[:selfright].present? || params[:rightholder].present?)
				 query = Rhinogallery::Image.joins(:gallery).select("rhinogallery_images.*").where(rhinogallery_galleries: {id: @gallery})
				 
				if params[:q].present?
					query = query.where('rhinogallery_images.tags like ? or rhinogallery_images.name like ?', "%#{params[:q]}%", "%#{params[:q]}%")
				end

				if params[:selfright].present?
					query = query.where(selfright: params[:selfright])
				end  

				if params[:rightholder].present?
					if params[:rightholder] == 'null'
						query = query.where('rightholder = ? or rightholder is null', '')
					else
						query = query.where(rightholder: params[:rightholder])
					end
				end
				@images = query.paginate(:page => params[:page], :per_page => 20).order('rhinogallery_images.name asc') 

			else
				@images = @gallery.images.paginate(:page => params[:page], :per_page => 20).order(created_at: :desc) 
			end
		end

		def move_up
			@gallery.move_higher
			redirect_to galleries_path
		end

		def move_down
			@gallery.move_lower
			redirect_to galleries_path
		end

		# GET /galleries/new
		def new
			@gallery = Gallery.new
		end

		# GET /galleries/1/edit
		def edit
		end

		# POST /galleries
		def create
			@gallery = Gallery.new(gallery_params)

			if @gallery.save
				redirect_to @gallery, notice: t('rhinogallery._GALLERY_SUCCESSFULLY_CREATED')
			else
				render :new
			end
		end

		# PATCH/PUT /galleries/1
		def update
			if @gallery.update(gallery_params)
				redirect_to @gallery, notice: t('rhinogallery._GALLERY_SUCCESSFULLY_UPDATED')
			else
				render :edit
			end
		end

		# DELETE /galleries/1
		def destroy
			@gallery.destroy
			redirect_to galleries_url, notice: t('rhinogallery._GALLERY_SUCCESSFULLY_UPDATED', name: @gallery.name)
		end

		def load_images

		end

		private
		# Use callbacks to share common setup or constraints between actions.
		def set_gallery
			@gallery = Gallery.find(params[:id])
		end

		# Only allow a trusted parameter "white list" through.
		def gallery_params
			params.fetch(:gallery).permit(:name, :slug, :image, :description, :active)
		end
	end
end

app/controllers/rhinogallery/images_controller.rb
require_dependency "rhinogallery/application_controller"
module Rhinogallery
  class ImagesController < ApplicationController
    before_action { authorize!(:manage, Rhinogallery::Image) }
    before_action :set_image, only: [:show, :edit, :update]

    # GET /images
    def index
      @images = Image.all
    end

    # GET /images/1
    def show
    end

    # GET /images/1/edit
    def edit
    end

    # POST /images
    def create
      name = File.basename(params[:name], File.extname(params[:name])) || File.basename(params[:file].original_filename, File.extname(params[:file].original_filename))
      image_params = {
        image: params[:file],
        name: name.capitalize,
        alt: name.capitalize,
        tags: tag_str(name),
        gallery: Rhinogallery::Gallery.find(params[:gallery_id])
      }
      @image = Image.new(image_params)
      @image.save!
      render :nothing => true
    end

    # PATCH/PUT /images/1
    def update
      if @image.update(image_params)
        redirect_to gallery_path(@image.gallery), notice: t('rhinogallery._IMAGE_SUCCESSFULLY_UPDATED')
      else
        render :edit
      end
    end

    # DELETE /images/1
    def destroy
      @image = Image.find(params[:id])
      @image.destroy
      respond_to do |format|
          format.html { redirect_to gallery_path(@image.gallery), notice: t('rhinogallery._IMAGE_SUCCESSFULLY_DELITED', name: @image.name) }          
          format.js {}
      end        
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_image
        @image = Gallery.find(params[:gallery_id]).images.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def image_params
        params.fetch(:image).permit(*Image::UPDATE_AVAILABLE_ATTRIBUTES)
      end

      def tag_str(str)
        res = ''
        res = str.humanize.downcase
        res = res.tr('(', '')
        res = res.tr(')', '')
        res = res.tr('-', ' ')
        res = res.tr(' ', ", ")
        return res
      end
  end
end

app/views/rhinogallery/galleries/_form.html.haml
= form_for @gallery do |f|
  = render 'rhinoart/shared/error_messages', object: f.object
  = hidden_field_tag :redirect_to, params[:redirect_to] if params[:redirect_to].present?

  .row-fluid
    .span4
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          = f.text_field :name, required: true, class: 'span12'

    .span4
      .control-group
        = f.label :slug, class: 'control-label'
        .controls
          = f.text_field :slug, class: 'span12'

    .span1
      .control-group
        = f.label :position, class: 'control-label'
        .controls
          = f.number_field :position, class: 'span12'
    .span1
      .control-group
        = f.label :active, class: 'control-label'
        .controls
          = f.check_box :active, class: 'span12'


  .control-group
    = f.label :image, class: 'control-label'
    .controls
      = f.file_field :image
      = f.hidden_field :image_cache
      %div
        = image_tag @gallery.image.thumb.url if @gallery.image.present?

  .row-fluid
    .span10
      .control-group
        = f.label :description, class: 'control-label'
        .controls
          = f.text_area :description, rows: '4', class: 'span12'

  .form-actions
    = f.submit t(:_BTN_SAVE), class: 'btn btn-primary', data: { disable_with: t(:_SAVING) }
    %a.btn.btn-success(href="#{rhinogallery.galleries_path}")=t(:_BACK)

app/views/rhinogallery/galleries/edit.html.haml
- provide(:title, "#{t(:_EDIT)}: #{@gallery.name}" )

.offset1
  %h1.offset-bottom1= "#{t(:_EDIT)}: #{@gallery.name}"
  = render 'form'

app/views/rhinogallery/galleries/index.html.haml
- provide(:title, t('rhinogallery._GALLERIES') )

.box-header{"data-original-title" => ""}
  %h2
    %i.halflings-icon.picture
    %span.break
    = t('rhinogallery._GALLERIES')
.box-content
  #DataTables_Table_0_wrapper.dataTables_wrapper{:role => "grid"}
    .row-fluid
      .btn-overlay
        %a.btn.btn-primary(href=new_gallery_path)
          %i.halflings-icon.plus
          =t(:_BTN_CREATE)
    %table.table.table-striped
      %thead
        %tr
          %th
          %th=t('rhinogallery._GALLERY_NAME')
          %th=t('rhinogallery._GALLERY_IMAGES_COUNT')
          %th=t(:_ACTIONS)
      %tbody
        - @galleries.each do |gallery|
          %tr
            %td
              - if !gallery.last?
                %a.icon-arrow-down(href="#{move_down_gallery_path(gallery)}")
              - if !gallery.first?
                %a.icon-arrow-up(href="#{move_up_gallery_path(gallery)}")
            %td
              %span= link_to gallery.name, gallery
            %td=gallery.images.size
            %td
              .btn-group
                %a.btn.dropdown-toggle.btn-mini{"data-toggle" => "dropdown", :href => "#"}
                  = t :_ACTIONS
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to(t(:_BTN_DELETE), gallery, {:method => :delete, 'data-confirm' => 'Are you sure?'})
                  %li= link_to(t(:_BTN_EDIT), edit_gallery_path(gallery))
                  %li= link_to(t(:_BTN_ADD_IMAGES), load_images_gallery_path(gallery))

app/views/rhinogallery/galleries/load_images.html.haml
- append_javascript 'rhinogallery/images_uploader'
- append_stylesheet 'rhinogallery/application'


%h1.offset-bottom1= "#{t('rhinogallery._GALLERY_LOADING_IMAGES')}: #{@gallery.name}"
#uploader
.form-actions
  .btn-overlay
    %a.btn.btn-primary(href="#{gallery_path(@gallery)}")= t(:_BACK)

:javascript
  window.gallery_images_path = '#{gallery_images_path(@gallery)}';

app/views/rhinogallery/galleries/new.html.haml
- provide(:title, t('rhinogallery._GALLERIES') )

.offset1
  %h1.offset-bottom1= t 'rhinogallery._NEW_GALLERY'
  = render 'form'

app/views/rhinogallery/galleries/show.html.haml
- provide(:title, "#{t('rhinogallery._GALLERY')}: #{@gallery.name}" )
- append_javascript 'lightbox'
- append_stylesheet 'lightbox'
- append_stylesheet 'rhinogallery/application'
- append_javascript 'rhinogallery/images'

.row-fluid
	.box-header
		%h2
			%i.halflings-icon.picture
			%span.break
			= "#{t('activerecord.models.rhinogallery/gallery.one')}: #{@gallery.name}"

	.box-content
		.row-fluid
			.span12
				= render 'rhinogallery/images/search_form'

		.row-fluid
			.span12
				.row-fluid.show-grid.offset-bottom1
					.span3
						= image_tag @gallery.image.thumb.url
					.span9
						%h1= @gallery.name
						%span= @gallery.description
				.row-fluid.show-grid.offset-bottom1
					= link_to(t(:_BTN_DELETE), @gallery, {:method => :delete, 'data-confirm' => 'Are you sure?', :class => 'btn btn-warning'})
					= link_to(t(:_BTN_EDIT), edit_gallery_path(@gallery), :class => 'btn btn-primary')
					= link_to(t(:_BTN_ADD_IMAGES), load_images_gallery_path(@gallery), :class => 'btn btn-success')
				.row-fluid.show-grid
					%legend= "Images (#{@images.count})"


				.row-fluid.show-grid.offset-bottom1
					.thumbnails
						- @images.in_groups_of(3, false) do |grp|
							.row-fluid
								- grp.each do |image| 
									= render 'rhinogallery/images/image_list', image: image

						= will_paginate @images

app/views/rhinogallery/images/_form.html.haml
= form_for(@image, url: gallery_image_path(@image.gallery, @image)) do |f|
  .form-horizontal
    = render 'rhinoart/shared/error_messages', object: f.object
    = hidden_field_tag :redirect_to, params[:redirect_to] if params[:redirect_to].present?

    .row-fluid
      .form-group.span2       
        - if !f.object.new_record?
          - image = @image.image.large.url
          = link_to image, class: 'image', data: { lightbox: :rhinogallery }, title: f.object.name do 
            = image_tag @image.image.thumb.url, class: 'media-object', alt: f.object.name, title: f.object.name, width: 120, height: 120

          = link_to 'Original', f.object.try(:image).url, target: :_blank

      .form-group.span3
        = f.label :image
        = f.file_field :image

      / .form-group.span5
      /   = f.label :asset_categories do
      /     = t :asset_categories
      /     = link_to t(:NEW_RECORD), new_admin_asset_category_path(redirect_to: request.fullpath)
      /   = f.select :asset_category_ids, AssetCategory::tree_for_select_list, {}, {:multiple => true, size: 6, class: 'form-control select2', placeholder: t('activerecord.placeholders.asset_category')}

    %br
    .row-fluid
      .form-group.span3
        = f.label :name
        = f.text_field :name, class: 'form-control span12'

      .form-group.span2
        = f.label :alt
        = f.text_field :alt, class: 'form-control span12'

      .form-group.span4
        = f.label :tags
        = f.text_field :tags, class: 'form-control span12'

      .form-group.span1
        = f.label :position
        = f.number_field :position, class: 'form-control span12'

    %br
    .row-fluid
      .form-group.span8
        = f.label :description
        = f.text_area :description, rows: 5, class: "span12"

      .form-group.span4
        = f.label :rightholder
        = f.select :rightholder, Rhinogallery::Image::RIGHTHOLDER_TYPES, {include_blank: true}, {class: 'form-control', style: 'margin-top: 5px;font-weight: normal;'}

        .row-fluid
          .form-group.col-sm-12
            %small= render 'rhinogallery/shared/change_by', object: f.object

    .row-fluid
      .form-actions
        = f.submit t(:_BTN_SAVE), class: 'btn btn-primary', data: { disable_with: t(:_SAVING) }
        = link_to t(:_BACK), @image.gallery, :class => 'btn btn-success'        

app/views/rhinogallery/images/_image_list.html.haml
= div_for(image, class: 'span4 offset-bottom1', data: {}) do
	.thumbnail
		.row-fluid
			.span4
				%a.image(href="#{image.image.large.url}" data-lightbox="rhinogallery-image")
					= image_tag image.image.thumb.url, width: 120, height: 120
			.span8.caption		
				%b=image.name
				%p= "Alt: #{image.alt}"
				%p= "Tags: #{image.tags}"
				%p= "Comment: #{image.description}"
				%small= render 'rhinogallery/shared/change_by', object: image

		.row-fluid
			.span12
				= link_to t(:_BTN_EDIT), edit_gallery_image_path(@gallery, image), :class => 'btn btn-primary'
				= link_to t(:_BTN_DELETE), image, {remote: true, :method => :delete, 'data-confirm' => 'Are you sure?', :class => 'btn btn-warning'}

app/views/rhinogallery/images/_search_form.html.haml
.navbar
	.navbar-inner.navbar-normal
		%a.brand Search filters
		= form_tag @gallery, method: :get, remote: request.xhr?, class: 'navbar-form', role: :form do 
			= hidden_field_tag :search, nil, value: 1 

			.pull-left{ style: 'margin-top: 9px; margin-right: 5px;' }= label_tag :rightholder
			= select_tag :rightholder, options_for_select(Rhinogallery::Image::RIGHTHOLDER_TYPES, params[:rightholder]), include_blank: 'All', class: 'form-control rightholder'

			= "&nbsp;".html_safe
			= text_field_tag :q, params[:q], placeholder: 'Searsh by: name, tags', class: 'form-control'

			= button_tag 'Search', class: 'btn btn-default'

app/views/rhinogallery/images/destroy.js.erb
$('#image_<%= @image.id %>').remove();

app/views/rhinogallery/images/edit.html.haml
- provide(:title, "#{t(:_EDIT)}: #{@image.name}" )
- append_javascript 'lightbox'
- append_stylesheet 'lightbox'
- append_javascript 'rhinogallery/images'
- append_stylesheet 'rhinogallery/application'

%h1.offset-bottom1= "#{t(:_EDIT)}: #{@image.name}"

= render 'form'

app/views/rhinogallery/shared/_change_by.html.haml
- if object.last_version_change_user.present?
	= "#{t('last_change_by')}:"
	- begin
		= link_to object.last_version_change_user.name, rhinoart.user_path(id: object.last_version_change_user.id, redirect_to: request.fullpath), target: :_blank		
	- rescue Exception => e
		User was deleted
	
= "#{l object.last_version_change_date, :format => :short}" if object.last_version_change_date.present?                                